### ISSUE TITLE
WalletConnect with Trust Wallet

### ISSUE THREAD

**Issue by buihuuloc** [WalletConnect/WalletConnectUnity#13] opened 2021-10-26 04:15 UTC
Hell there,

Is there any special setup for Trust Wallet?

**Comment by ecp4224** [comment] 2021-11-10 17:31
PR #21 seems to be working with Trust Wallet. I will be testing on mobile as well but please let me know if this PR resolves your issue

**Comment by gigajuwels** [comment] 2021-12-08 05:20
@buihuuloc, PR #21 has been merged into main, are you still experiencing this issue?

**Comment by gigajuwels** [comment] 2021-12-10 04:18
Confirmed working on Mobile (android)

**Closed by gigajuwels** 2021-12-10 04:18 UTC
Labels: bug
