### ISSUE TITLE
TimeoutException: socket stalled

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#93] opened 2023-08-14 01:32 UTC
Hello, I would like to ask when the Unity library will be updated. After packaging, socket errors have been reported continuously

**Comment by gigajuwels** [comment] 2023-09-14 14:07
hi @GaoG001108  this issue should be fixed now, as the simple dapp demo is fully working on desktop and mobile. Can you confirm this issue is resolved? If not, can you provide some details on how you reproduce this and what error you are getting?
Thank you

**Comment by gigajuwels** [comment] 2023-09-27 01:47
duplicate of issue #101

**Closed by gigajuwels** 2023-09-27 01:47 UTC
Labels: duplicate
