### ISSUE TITLE
transaction error

### ISSUE THREAD

**Issue by GaoG001108** [WalletConnect/WalletConnectUnity#85] opened 2023-07-21 08:12 UTC
When I successfully call EthGetBalance and then call EthSendTransaction, there will be errors reported, including requesting other interfaces。
My usage scenario is when I first use personal_ Sign successfully, and then my project must use ETH_ SendTransaction, and then report the same error as above.
![image (2)](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/453f825f-b41e-469b-b5fd-6c45cef649bb)
![image](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/a400511b-91a8-4de1-a44d-00f1837fcc19)
![image (1)](https://github.com/WalletConnect/WalletConnectUnity/assets/121652682/740723be-edd1-4e92-a685-292e6dc436ea)

**Comment by dpradell-dev** [comment] 2023-07-23 15:17
Hey @GaoG001108 I'm sorry I can not help you with your request as I'm struggling myself with this. Could you share how did you achieve to succeed with eth_personalSign?

**Comment by gigajuwels** [comment] 2023-09-14 14:34
Hi @GaoG001108 and @dpradell-dev The specific error you posted should be resolved with the latest commit. However, doing `EthGetBalance` through WalletConnect may not be supported by your wallet. See #96

**Comment by gigajuwels** [comment] 2023-09-27 01:49
This issue is a duplicate of #96

**Closed by gigajuwels** 2023-09-27 01:49 UTC
Labels: duplicate
